In [1]:
import os


os.environ['CUDA_VISIBLE_DEVICES'] = '1'
os.environ['https_proxy'] = 'http://172.17.0.1:1081'
os.environ['HF_TOKEN'] = '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'


In [2]:
import torch
from axolotl.models.eagle import EaModel


model = EaModel.from_pretrained(
	base_model_path='/models/Meta-Llama-3-8B-Instruct',
	ea_model_path='yuhuili/EAGLE-LLaMA3-Instruct-8B',
	total_token=11,
	depth=5,
	top_k=3,
	torch_dtype=torch.bfloat16,
	low_cpu_mem_usage=True,
	device_map="auto"
)
model.eval()

tokenizer = model.get_tokenizer()
tokenizer

/root/work/axolotl/env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Instantiating LlamaAttention without passing a `layer_idx` is not recommended and will lead to errors during the forward call if caching is used. Please make sure to provide a `layer_idx` when creating this class.
Loading checkpoint shards: 100%|██████████| 4/4 [00:27<00:00,  6.83s/it]


PreTrainedTokenizerFast(name_or_path='/models/Meta-Llama-3-8B-Instruct', vocab_size=128000, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|begin_of_text|>', 'eos_token': '<|end_of_text|>', 'unk_token': '<|unk|>', 'sep_token': '<|sep|>', 'cls_token': '<|cls|>', 'mask_token': '<|mask|>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	128000: AddedToken("<|begin_of_text|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128001: AddedToken("<|end_of_text|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128002: AddedToken("<|reserved_special_token_0|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128003: AddedToken("<|reserved_special_token_1|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128004: AddedToken("<|reserved_special_token_2|>", 

In [3]:
model.base_model.base_model.layers[0].self_attn.k_proj.weight[:4, :4].tolist()

[[-0.10302734375, -0.154296875, 0.0732421875, -0.05078125],
 [-0.05615234375, -0.08642578125, 0.0186767578125, 0.0005340576171875],
 [-0.0201416015625, -0.05615234375, 0.0419921875, -0.00762939453125],
 [0.041259765625, 0.01153564453125, -0.0031890869140625, 0.025390625]]

In [4]:
model.base_model.base_model.layers[0].self_attn.q_proj.weight[:4, :4].tolist()

[[-0.0028533935546875, -0.02880859375, -0.003173828125, -0.0072021484375],
 [-0.0125732421875, -0.0693359375, -0.003448486328125, -0.0012969970703125],
 [-0.018798828125, -0.0458984375, -0.00457763671875, -0.0185546875],
 [0.0142822265625, 0.06201171875, -0.0013275146484375, -0.004364013671875]]

In [5]:
model.base_model.base_model.layers[0].self_attn.v_proj.weight[:4, :4].tolist()

[[0.009033203125, -0.00238037109375, -0.000362396240234375, 0.004730224609375],
 [0.0003948211669921875,
  -0.0038299560546875,
  -7.62939453125e-05,
  0.00994873046875],
 [0.00994873046875, 0.0008087158203125, 0.00142669677734375, -0.00830078125],
 [0.00634765625, 0.000919342041015625, 0.000553131103515625, 0.00628662109375]]

In [ ]:
prompt = "You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\\n\\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information."

input_ids = tokenizer.encode(prompt, add_special_tokens=True, return_tensors='pt')
input_ids.shape, input_ids

(torch.Size([1, 104]),
 tensor([[128000,   2675,    527,    264,  11190,     11,  49150,    323,  10978,
           18328,     13,  24119,   4320,    439,   1520,   3725,    439,   3284,
              11,   1418,   1694,   6220,     13,    220,   4718,  11503,   1288,
             539,   2997,    904,  28856,     11,  89735,     11,  25185,     11,
           64882,     11,  21503,     11,  11660,     11,    477,  12079,   2262,
              13,   5321,   6106,    430,    701,  14847,    527,  40418,  74315,
             323,   6928,    304,   7138,   7255,     77,   1734,   2746,    264,
            3488,   1587,    539,   1304,    904,   5647,     11,    477,    374,
             539,   2144,   1870,  56887,     11,  10552,   3249,   4619,    315,
           36864,   2555,    539,   4495,     13,   1442,    499,   1541,    956,
            1440,    279,   4320,    311,    264,   3488,     11,   4587,   1541,
             956,   4430,    905,   2038,     13]]))

In [7]:
model.to('cuda')
output_ids, new_token, idx, accept_lengths = model.eagenerate(
	input_ids.cuda(),
	temperature=0,
	log=True,
	is_llama3=True,
	max_new_tokens=16,
	max_length=8192,
	pad_head_zero=False,
)

output_ids, new_token, idx, accept_lengths

hidden_states[0, -1, :4]=tensor([-0.0255, -0.0391,  0.6328, -0.2324], device='cuda:0',
       dtype=torch.bfloat16)
(_em_hs1 - em_hs1[:, -1]).norm()=tensor(0., device='cuda:0', dtype=torch.bfloat16)
(fcw - self.fc.weight).norm()=tensor(0., device='cuda:0', dtype=torch.bfloat16)
(hs2 - hidden_states[:, -1]).norm()=tensor(0., device='cuda:0', dtype=torch.bfloat16)
hs2[0, :4]=tensor([-0.0255, -0.0391,  0.6328, -0.2324], device='cuda:0',
       dtype=torch.bfloat16)
hs2_p[0, :4]=tensor([-0.0255, -0.0383,  0.6289, -0.2344], device='cuda:0',
       dtype=torch.bfloat16)
hs2_p2[0, :4]=tensor([-0.0255, -0.0383,  0.6289, -0.2344], device='cuda:0',
       dtype=torch.bfloat16)
hs2_p3[0, -1, :4]=tensor([-0.0255, -0.0391,  0.6328, -0.2324], device='cuda:0',
       dtype=torch.bfloat16)
(hs2 - hs2_p).norm()=tensor(0.1221, device='cuda:0', dtype=torch.bfloat16)
(hs2 - hs2_p2).norm()=tensor(0.1221, device='cuda:0', dtype=torch.bfloat16)
(hs2 - hs2_p3[0, -1]).norm()=tensor(0., device='cuda:0', dtype=t

NameError: name 'exit' is not defined

In [9]:
len(model.past_key_values)

32

In [12]:
model.past_key_values_data[0].shape

torch.Size([64, 1, 8, 8192, 128])

In [10]:
model.ea_layer.stable_kv[0][0].shape

torch.Size([1, 8, 122, 128])

In [8]:
torch.save(model.ea_layer.stable_kv[0], './stable_kv.pt')
model.ea_layer.stable_kv[0][0].mean(dim=[0, 1, 3])

tensor([ 0.0317,  0.0298, -0.0151, -0.0425,  0.0186, -0.0474,  0.0869,  0.0270,
         0.0161,  0.0454,  0.0192,  0.0091, -0.0544, -0.0050, -0.0239,  0.0427,
        -0.0093,  0.1338,  0.0640,  0.0215, -0.0068,  0.0913,  0.0376,  0.0530,
         0.0103,  0.0654,  0.0850,  0.0082, -0.0427, -0.0466, -0.0500, -0.0693,
         0.0693, -0.0244, -0.0393, -0.0718, -0.0479,  0.0065, -0.0398,  0.0035,
         0.0203, -0.0206, -0.0879, -0.0306,  0.0048, -0.0349,  0.0110,  0.0057,
        -0.0219, -0.0106,  0.0007,  0.0317,  0.0569,  0.1064,  0.0181,  0.0552,
         0.0613,  0.0825, -0.0250,  0.0283, -0.0195, -0.1147, -0.0566, -0.0165,
         0.0703, -0.0222, -0.0248, -0.0298,  0.0012, -0.0270,  0.0072,  0.0084,
        -0.0371, -0.0030,  0.0248,  0.0297, -0.0488,  0.0035, -0.0017,  0.0330,
        -0.0037,  0.0096,  0.0090, -0.0156,  0.0145,  0.0153, -0.0757, -0.0065,
         0.0118,  0.0132,  0.0496,  0.0222,  0.0029,  0.0103, -0.0278,  0.0070,
        -0.0126, -0.0108,  0.0500,  0.00

In [14]:
model.ea_layer.stable_kv[0][0].mean(dim=[0, 1, 3]).roll(shifts=1, dims=0)

tensor([ 0.0121,  0.0327,  0.0293, -0.0148, -0.0430,  0.0190, -0.0483,  0.0869,
         0.0262,  0.0172,  0.0461,  0.0190,  0.0090, -0.0530, -0.0057, -0.0229,
         0.0410, -0.0085,  0.1348,  0.0649,  0.0209, -0.0068,  0.0913,  0.0393,
         0.0549,  0.0102,  0.0645,  0.0859,  0.0099, -0.0417, -0.0457, -0.0486,
        -0.0688,  0.0688, -0.0244, -0.0403, -0.0723, -0.0457,  0.0073, -0.0396,
         0.0042,  0.0203, -0.0201, -0.0879, -0.0320,  0.0044, -0.0352,  0.0114,
         0.0064, -0.0216, -0.0107, -0.0005,  0.0312,  0.0564,  0.1055,  0.0172,
         0.0552,  0.0618,  0.0820, -0.0243,  0.0291, -0.0198, -0.1152, -0.0554,
        -0.0152,  0.0713, -0.0225, -0.0248, -0.0294,  0.0009, -0.0277,  0.0075,
         0.0083, -0.0359, -0.0024,  0.0242,  0.0289, -0.0488,  0.0037, -0.0018,
         0.0330, -0.0047,  0.0093,  0.0090, -0.0146,  0.0150,  0.0154, -0.0757,
        -0.0076,  0.0120,  0.0144,  0.0498,  0.0222,  0.0030,  0.0120, -0.0264,
         0.0070, -0.0127, -0.0103,  0.04

In [13]:
model.ea_layer.stable_kv[0][1].mean(dim=[0, 1, 3])

tensor([ 0.0332, -0.0623, -0.0442, -0.0157,  0.0004,  0.0036, -0.0029, -0.0260,
        -0.0051, -0.0125,  0.0022, -0.0238,  0.0483,  0.0063,  0.0134,  0.0172,
         0.0134,  0.0192,  0.0237,  0.0063, -0.0135, -0.0113, -0.0204,  0.0042,
         0.0095,  0.0010, -0.0292, -0.0266, -0.0312, -0.0378, -0.0058, -0.0581,
         0.0074, -0.0508,  0.0112, -0.0179,  0.0128, -0.0300,  0.0493, -0.0330,
         0.0111, -0.0442, -0.0605, -0.0055,  0.0190,  0.0060,  0.0393,  0.0260,
        -0.0056,  0.0292,  0.0052, -0.0082, -0.0128,  0.0021,  0.0178,  0.0425,
         0.0293,  0.0432, -0.0189,  0.0339,  0.0469,  0.0010, -0.0190,  0.0080,
         0.0223, -0.0205, -0.0084, -0.0199, -0.0059, -0.0049,  0.0165, -0.0181,
        -0.0027,  0.0060,  0.0120, -0.0061,  0.0043,  0.0386,  0.0267,  0.0050,
         0.0072,  0.0206,  0.0079, -0.0114,  0.0283,  0.0092,  0.0210, -0.0063,
         0.0068,  0.0459,  0.0322,  0.0269,  0.0170,  0.0204,  0.0145,  0.0444,
         0.0217,  0.0156,  0.0070,  0.00

In [8]:
model.ea_layer.stable_kv[0][0][0, :, :].mean(dim=[0, 2])

tensor([ 0.0317,  0.0298, -0.0151, -0.0425,  0.0186, -0.0474,  0.0869,  0.0270,
         0.0161,  0.0454,  0.0192,  0.0091, -0.0544, -0.0050, -0.0239,  0.0427,
        -0.0093,  0.1338,  0.0640,  0.0215, -0.0068,  0.0913,  0.0376,  0.0530,
         0.0103,  0.0654,  0.0850,  0.0082, -0.0427, -0.0466, -0.0500, -0.0693,
         0.0693, -0.0244, -0.0393, -0.0718, -0.0479,  0.0065, -0.0398,  0.0035,
         0.0203, -0.0206, -0.0879, -0.0306,  0.0048, -0.0349,  0.0110,  0.0057,
        -0.0219, -0.0106,  0.0007,  0.0317,  0.0569,  0.1064,  0.0181,  0.0552,
         0.0613,  0.0825, -0.0250,  0.0283, -0.0195, -0.1147, -0.0566, -0.0165,
         0.0703, -0.0222, -0.0248, -0.0298,  0.0012, -0.0270,  0.0072,  0.0084,
        -0.0371, -0.0030,  0.0248,  0.0297, -0.0488,  0.0035, -0.0017,  0.0330,
        -0.0037,  0.0096,  0.0090, -0.0156,  0.0145,  0.0153, -0.0757, -0.0065,
         0.0118,  0.0132,  0.0496,  0.0222,  0.0029,  0.0103, -0.0278,  0.0070,
        -0.0126, -0.0108,  0.0500,  0.00

In [9]:
model.ea_layer.stable_kv[0][1][0, :, :].mean(dim=[0, 2])

tensor([ 0.0337, -0.0625, -0.0442, -0.0157,  0.0005,  0.0034, -0.0032, -0.0258,
        -0.0052, -0.0122,  0.0017, -0.0234,  0.0486,  0.0057,  0.0131,  0.0177,
         0.0135,  0.0188,  0.0243,  0.0070, -0.0141, -0.0108, -0.0212,  0.0049,
         0.0098,  0.0007, -0.0293, -0.0262, -0.0308, -0.0378, -0.0063, -0.0588,
         0.0075, -0.0508,  0.0107, -0.0175,  0.0126, -0.0305,  0.0500, -0.0325,
         0.0115, -0.0435, -0.0605, -0.0050,  0.0199,  0.0060,  0.0388,  0.0264,
        -0.0052,  0.0291,  0.0055, -0.0086, -0.0119,  0.0023,  0.0178,  0.0427,
         0.0294,  0.0425, -0.0182,  0.0332,  0.0461,  0.0007, -0.0187,  0.0077,
         0.0203, -0.0209, -0.0091, -0.0208, -0.0064, -0.0052,  0.0164, -0.0183,
        -0.0020,  0.0067,  0.0121, -0.0061,  0.0036,  0.0376,  0.0266,  0.0053,
         0.0065,  0.0206,  0.0079, -0.0117,  0.0282,  0.0090,  0.0204, -0.0067,
         0.0061,  0.0461,  0.0317,  0.0266,  0.0167,  0.0200,  0.0150,  0.0447,
         0.0211,  0.0156,  0.0065,  0.00

---

In [8]:
torch.save(model.base_model.base_model.layers[0].self_attn.q_proj.weight, 'q_proj0.pt')

In [26]:
torch.save(model.base_model.base_model.layers[0].self_attn.k_proj.weight, 'k_proj0.pt')

In [27]:
h0 = torch.load('./hidden_states0.pt')
q_proj = torch.load('./q_proj0.pt')
k_proj = torch.load('./k_proj0.pt')

(h0.shape, q_proj.shape, k_proj.shape), (h0.dtype, q_proj.dtype, k_proj.dtype)

/tmp/ipykernel_956337/3807054409.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  h0 = torch.load('./hidden_states0.pt')
/tmp/ipykernel_956337/3807054409.py:2: FutureWarn

((torch.Size([1, 104, 4096]),
  torch.Size([4096, 4096]),
  torch.Size([1024, 4096])),
 (torch.bfloat16, torch.bfloat16, torch.bfloat16))

In [20]:
h0[:, :2, :4].tolist()

[[[-0.00057220458984375,
   0.00689697265625,
   -0.01422119140625,
   -6.198883056640625e-05],
  [-0.0260009765625, 0.021484375, -0.43359375, 0.01336669921875]]]

In [19]:
q_proj[:4, :4].tolist()

[[-0.0028533935546875, -0.02880859375, -0.003173828125, -0.0072021484375],
 [-0.0125732421875, -0.0693359375, -0.003448486328125, -0.0012969970703125],
 [-0.018798828125, -0.0458984375, -0.00457763671875, -0.0185546875],
 [0.0142822265625, 0.06201171875, -0.0013275146484375, -0.004364013671875]]

In [28]:
k_proj[:4, :4].tolist()

[[-0.10302734375, -0.154296875, 0.0732421875, -0.05078125],
 [-0.05615234375, -0.08642578125, 0.0186767578125, 0.0005340576171875],
 [-0.0201416015625, -0.05615234375, 0.0419921875, -0.00762939453125],
 [0.041259765625, 0.01153564453125, -0.0031890869140625, 0.025390625]]

In [25]:
q0 = torch.matmul(h0, q_proj.transpose(-1, -2))
q0.shape, q0.dtype, q0[:, :2, :4].tolist()

(torch.Size([1, 104, 4096]),
 torch.bfloat16,
 [[[-0.0537109375, 0.34375, 0.306640625, -0.1865234375],
   [0.49609375, 1.40625, 1.0078125, -1.6171875]]])

In [29]:
k0 = torch.matmul(h0, k_proj.transpose(-1, -2))
k0.shape, k0.dtype, k0[:, :2, :4].tolist()

(torch.Size([1, 104, 1024]),
 torch.bfloat16,
 [[[0.62890625, 1.0390625, 1.0078125, -0.68359375],
   [7.34375, 2.8125, 1.5546875, -1.65625]]])

In [36]:
import torch.nn.functional as F


k0_l = F.linear(h0, k_proj)
k0_l[:, :2, :4].tolist()

[[[0.62890625, 1.0390625, 1.0078125, -0.68359375],
  [7.34375, 2.8125, 1.5546875, -1.65625]]]

In [30]:
k_proj_p = torch.load('./k_proj0-pp.pt')
k_proj_p.shape

/tmp/ipykernel_956337/2911813159.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  k_proj_p = torch.load('./k_proj0-pp.pt')


torch.Size([2048, 4096])

In [35]:
dk = k_proj - k_proj_p[:1024]
(dk[:] == 0).sum() / 1024

tensor(4096., device='cuda:0')

In [38]:
h0_p = torch.load('./hidden_states0-pp.pt')
h0_p.shape

/tmp/ipykernel_956337/2737884646.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  h0_p = torch.load('./hidden_states0-pp.pt')


torch.Size([104, 4096])

In [42]:
dh = h0[0] - h0_p
(dh[:] == 0).sum()

tensor(425984, device='cuda:0')

In [44]:
h0[0, 0, 0].item()

-0.00057220458984375

In [49]:
ux = torch.load('./U-x.pt')
uw = torch.load('./U-weight.pt')
ur = torch.load('./U-result.pt')

(ux.shape, uw.shape, ur.shape), (ux.dtype, uw.dtype, ur.dtype)

/tmp/ipykernel_956337/1998232343.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ux = torch.load('./U-x.pt')
/tmp/ipykernel_956337/1998232343.py:2: FutureWarning: You ar

((torch.Size([104, 4096]), torch.Size([6144, 4096]), torch.Size([104, 6144])),
 (torch.bfloat16, torch.bfloat16, torch.bfloat16))

In [51]:
(ux == h0[0]).sum() / 4096

tensor(104., device='cuda:0')

In [60]:
(k_proj == uw[4096:4096+1024]).sum() / 4096

tensor(1024., device='cuda:0')

In [66]:
du = ur[:, 4096:4096+1024] == k0_l[0]
du

tensor([[ True,  True,  True,  ..., False,  True,  True],
        [False,  True,  True,  ...,  True,  True,  True],
        [ True,  True, False,  ..., False,  True,  True],
        ...,
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True, False,  True]], device='cuda:0')

In [69]:
du.float().mean()

tensor(0.7472, device='cuda:0')

In [70]:
ur.dtype, k0_l.dtype

(torch.bfloat16, torch.bfloat16)

In [71]:
tr = F.linear(ux, uw)
tr.shape, tr.dtype

(torch.Size([104, 6144]), torch.bfloat16)

In [76]:
(tr == ur).float().mean()

tensor(1., device='cuda:0')

In [79]:
tr_partial = F.linear(ux, uw[4096:4096+1024])
tr_partial == tr[:, 4096:4096+1024]

tensor([[ True,  True,  True,  ..., False,  True,  True],
        [False,  True,  True,  ...,  True,  True,  True],
        [ True,  True, False,  ..., False,  True,  True],
        ...,
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True, False,  True]], device='cuda:0')

In [81]:
tr_m = torch.matmul(ux, uw.transpose(0, 1))
tr_partial_m = torch.matmul(ux, uw[4096:4096+1024].transpose(0, 1))

tr_m[:, 4096:4096+1024]==tr_partial_m

tensor([[ True,  True,  True,  ..., False,  True,  True],
        [False,  True,  True,  ...,  True,  True,  True],
        [ True,  True, False,  ..., False,  True,  True],
        ...,
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True, False,  True]], device='cuda:0')

In [88]:
fux, fuw = ux.float(), uw.float()

ftr_m = torch.matmul(fux, fuw.transpose(0, 1))
ftr_partial_m = torch.matmul(fux, fuw[4096:4096+1024].transpose(0, 1))

(ftr_m[:, 4096:4096+1024].to(torch.bfloat16)==ftr_partial_m.to(torch.bfloat16)).float().mean()

tensor(0.9999, device='cuda:0')

---

In [14]:
k0 = torch.load('./k_cache0.pt')
k0.shape, k0

/tmp/ipykernel_1000162/1526401327.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  k0 = torch.load('./k_cache0.pt')


(torch.Size([8, 128]),
 tensor([[ 0.9805, -0.3789, -0.4219,  ...,  1.8281,  2.7500, -1.4609],
         [-0.4434, -0.0292,  0.8047,  ...,  3.3750, -1.1797,  2.7188],
         [ 0.2490,  0.3340, -0.5703,  ...,  1.7656,  0.6406,  1.8125],
         ...,
         [-0.1631, -1.4297,  0.7969,  ...,  2.8750,  2.6562,  3.0781],
         [ 0.8164, -0.2715,  0.9258,  ..., -0.4297, -6.8750,  2.0000],
         [ 1.1094, -0.4473,  0.0654,  ...,  2.8438, -0.1914, -2.5156]],
        device='cuda:0', dtype=torch.bfloat16))

---

In [15]:
lh = torch.load('./last_hidden.pt')
lh0 = torch.load('./last_hidden0.pt')
lh1 = torch.load('./last_hidden1.pt')
lh2 = torch.load('./last_hidden2.pt')

lh.shape, lh0.shape, lh1.shape

/tmp/ipykernel_1007498/2684001431.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  lh = torch.load('./last_hidden.pt')
/tmp/ipykernel_1007498/2684001431.py:2: FutureWarni

(torch.Size([1, 4096]), torch.Size([1, 4096]), torch.Size([1, 4096]))

In [16]:
(lh - lh0).mean(), (lh - lh1).mean(), (lh - lh2).mean()

(tensor(0.0171, device='cuda:0', dtype=torch.bfloat16),
 tensor(0.0171, device='cuda:0', dtype=torch.bfloat16),
 tensor(0.0170, device='cuda:0', dtype=torch.bfloat16))

In [17]:
(lh0 - lh1).mean(), (lh0 - lh2).mean()

(tensor(-0.0001, device='cuda:0', dtype=torch.bfloat16),
 tensor(-0.0001, device='cuda:0', dtype=torch.bfloat16))

---

In [10]:
import torch

out = torch.load('./out_hidden-1.pt')
out.shape

/tmp/ipykernel_1342401/2062146244.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  out = torch.load('./out_hidden-1.pt')


torch.Size([1, 104, 4096])

In [9]:
out[0, -1, :10]

tensor([ 0.7266, -0.1602, -1.4453, -2.3750, -1.8750,  0.4922, -1.3438,  1.3906,
        -4.0625, -0.2578], device='cuda:0', dtype=torch.bfloat16)

In [12]:
import torch


out_pp = torch.load('./out_hidden-1-pp.pt')
diff = out[0, -1] - out_pp[0]
(diff.norm() / out[0, -1].norm()).item(), diff

/tmp/ipykernel_1342401/1068336853.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  out_pp = torch.load('./out_hidden-1-pp.pt')


(0.00909423828125,
 tensor([-0.0234, -0.0020,  0.0078,  ...,  0.0059,  0.0078, -0.0312],
        device='cuda:0', dtype=torch.bfloat16))

In [8]:
out_ppv1 = torch.load('./out_hidden-1-ppv1.pt')
out_ppv1.shape

/tmp/ipykernel_1259441/2495122864.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  out_ppv1 = torch.load('./out_hidden-1-ppv1.pt')


torch.Size([1, 104, 4096])

In [9]:
diff2 = out[0, -1] - out_ppv1[0, -1]
(diff2.norm() / out[0, -1].norm()).item(), diff2

(0.0,
 tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0', dtype=torch.bfloat16))

---

In [18]:
stable_kv = torch.load('/root/work/axolotl/tests/stable_kv.pt')
stable_kv[0].shape

/tmp/ipykernel_1247116/2823696537.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  stable_kv = torch.load('/root/work/axolotl/tests/stable_kv.pt')


torch.Size([1, 8, 122, 128])

In [2]:
import torch


h0 = torch.load('./hidden_states0.pt')
h0.shape

/tmp/ipykernel_1253443/2651928524.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  h0 = torch.load('./hidden_states0.pt')


torch.Size([1, 104, 4096])

In [3]:
h0[0, -1, :10]

tensor([-1.6875, -2.8594, -1.8125, -1.1562,  0.3223, -1.2891,  0.1182,  2.0312,
        -4.0625, -2.0781], device='cuda:0', dtype=torch.bfloat16)

---

In [8]:
q, k, v, attn_output = torch.load('./q.pt'), torch.load('./k.pt'), torch.load('./v.pt'), torch.load('./attn_output.pt')
q.shape, k.shape, v.shape, attn_output.shape

/tmp/ipykernel_1384130/2326698417.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  q, k, v, attn_output = torch.load('./q.pt'), torch.load('./k.pt'), torch.load('./v.pt')

(torch.Size([1, 32, 104, 128]),
 torch.Size([1, 8, 104, 128]),
 torch.Size([1, 8, 104, 128]),
 torch.Size([1, 32, 104, 128]))

In [ ]:
q, k, v = q[:, :, -1].reshape(1, -1), k[:, :, -1].reshape(1, -1), v[:, :, -1].reshape(1, -1)
attn_output = attn_output[:, :, -1].reshape(1, -1)
q.shape, k.shape, v.shape, attn_output.shape

(torch.Size([1, 4096]),
 torch.Size([1, 1024]),
 torch.Size([1, 1024]),
 torch.Size([1, 4096]))

In [10]:
q_pp, k_pp, v_pp, attn_output_pp = torch.load('./q-pp.pt'), torch.load('./k-pp.pt'), torch.load('./v-pp.pt'), torch.load('./attn_output-pp.pt')
q_pp.shape, k_pp.shape, v_pp.shape, attn_output_pp.shape

/tmp/ipykernel_1384130/61718048.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  q_pp, k_pp, v_pp, attn_output_pp = torch.load('./q-pp.pt'), torch.load('./k-pp.pt'), torc

(torch.Size([1, 4096]),
 torch.Size([1, 1024]),
 torch.Size([1, 1024]),
 torch.Size([1, 4096]))

In [11]:
(q - q_pp).norm() / q.norm()

tensor(0.0027, device='cuda:0', dtype=torch.bfloat16)

In [12]:
(k - k_pp).norm() / k.norm()

tensor(0.0023, device='cuda:0', dtype=torch.bfloat16)

In [13]:
(v - v_pp).norm() / v.norm()

tensor(0.0031, device='cuda:0', dtype=torch.bfloat16)

In [16]:
(attn_output - attn_output_pp).norm() / attn_output.norm()

tensor(0.0069, device='cuda:0', dtype=torch.bfloat16)

---

In [9]:
hidden_states = torch.load('./hidden_states.pt')[:, -1]
hidden_states.shape

/tmp/ipykernel_1386543/2203874551.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  hidden_states = torch.load('./hidden_states.pt')[:, -1]


torch.Size([1, 4096])

In [8]:
hidden_states_pp = torch.load('./hidden_states-pp.pt')
hidden_states_pp.shape

/tmp/ipykernel_1386543/533311294.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  hidden_states_pp = torch.load('./hidden_states-pp.pt')


torch.Size([1, 4096])

In [11]:
(hidden_states - hidden_states_pp).norm() / hidden_states.norm()

tensor(0.0025, device='cuda:0', dtype=torch.bfloat16)