In [1]:
import torch

In [2]:
o1 = torch.load('./out_hidden-1.pt')
o1.shape

/tmp/ipykernel_1398232/3280205847.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  o1 = torch.load('./out_hidden-1.pt')


torch.Size([1, 104, 4096])

In [4]:
o2 = torch.load('./tensor-eagle/hs6.pt')
o2.shape

/tmp/ipykernel_1398232/546704790.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  o2 = torch.load('./tensor-eagle/hs6.pt')


torch.Size([1, 104, 4096])

In [8]:
hs1 = torch.load('./tensor-eagle/hs1.pt')
hs2 = torch.load('./tensor-eagle/hs2.pt')
hs3 = torch.load('./tensor-eagle/hs3.pt')
hs4 = torch.load('./tensor-eagle/hs4.pt')
hs5 = torch.load('./tensor-eagle/hs5.pt')
hs6 = torch.load('./tensor-eagle/hs6.pt')
q = torch.load('./tensor-eagle/q.pt')
k = torch.load('./tensor-eagle/k.pt')
v = torch.load('./tensor-eagle/v.pt')
qp = torch.load('./tensor-eagle/qp.pt')
kp = torch.load('./tensor-eagle/kp.pt')
attn_output1 = torch.load('./tensor-eagle/attn_output1.pt')
attn_output2 = torch.load('./tensor-eagle/attn_output2.pt')
embeds = torch.load('./tensor-eagle/embeds.pt')

(hs1.shape, hs2.shape, hs3.shape, hs4.shape, hs5.shape, hs6.shape), (q.shape, k.shape, v.shape, qp.shape, kp.shape), (attn_output1.shape, attn_output2.shape), embeds.shape

/tmp/ipykernel_1398232/2686817142.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  hs1 = torch.load('./tensor-eagle/hs1.pt')
/tmp/ipykernel_1398232/2686817142.py:2: Futur

((torch.Size([1, 4096]),
  torch.Size([1, 4096]),
  torch.Size([1, 4096]),
  torch.Size([1, 4096]),
  torch.Size([1, 4096]),
  torch.Size([1, 4096])),
 (torch.Size([1, 4096]),
  torch.Size([1, 1024]),
  torch.Size([1, 1024]),
  torch.Size([1, 4096]),
  torch.Size([1, 1024])),
 (torch.Size([1, 4096]), torch.Size([1, 4096])),
 torch.Size([1, 4096]))

: 

In [4]:
fc = torch.load('./tensor-eagle/fc.pt')
fc.shape, fc.dtype

/tmp/ipykernel_1410672/3226135465.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  fc = torch.load('./tensor-eagle/fc.pt')


(torch.Size([4096, 8192]), torch.bfloat16)

In [7]:
em_hs1 = torch.load('./tensor-eagle/em_hs1.pt')
em_hs1.shape, fc.dtype

/tmp/ipykernel_1410672/1384302525.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  em_hs1 = torch.load('./tensor-eagle/em_hs1.pt')


(torch.Size([1, 8192]), torch.bfloat16)

In [6]:
torch.save(em_hs1[:, -1], './tensor-eagle/em_hs1.pt')

---

In [12]:
em_hs1 = torch.load('/root/work/axolotl/tests/tensor-eagle/em_hs1.pt')
fcw = torch.load('/root/work/axolotl/tests/tensor-eagle/fc.pt')
hs2 = torch.load('/root/work/axolotl/tests/tensor-eagle/hs2.pt')

em_hs1.shape, fcw.shape, hs2.shape

/tmp/ipykernel_1415501/3418034252.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  em_hs1 = torch.load('/root/work/axolotl/tests/tensor-eagle/em_hs1.pt')
/tmp/ipykernel_1

(torch.Size([1, 8192]), torch.Size([4096, 8192]), torch.Size([1, 4096]))

In [13]:
fc = torch.nn.Linear(8192, 4096, bias=False)
fc.weight = fcw
fc

Linear(in_features=8192, out_features=4096, bias=False)

In [14]:
hs2_p = fc(em_hs1)
hs2_p.shape

torch.Size([1, 4096])

In [15]:
hs2 - hs2_p

tensor([[ 0.0000, -0.0007,  0.0039,  ...,  0.0000,  0.0000,  0.0006]],
       device='cuda:0', dtype=torch.bfloat16, grad_fn=<SubBackward0>)

In [22]:
hs2[0, :4], hs2_p[0, :4]

(tensor([-0.0255, -0.0391,  0.6328, -0.2324], device='cuda:0',
        dtype=torch.bfloat16),
 tensor([-0.0255, -0.0383,  0.6289, -0.2344], device='cuda:0',
        dtype=torch.bfloat16, grad_fn=<SliceBackward0>))

In [16]:
hs2_p2 = torch.matmul(em_hs1, fcw.transpose(0, 1))
hs2_p2.shape

torch.Size([1, 4096])

In [17]:
hs2 - hs2_p2

tensor([[ 0.0000, -0.0007,  0.0039,  ...,  0.0000,  0.0000,  0.0006]],
       device='cuda:0', dtype=torch.bfloat16, grad_fn=<SubBackward0>)

In [18]:
hs2_p3 = torch.nn.functional.linear(em_hs1, fcw)
hs2_p3.shape

torch.Size([1, 4096])

In [19]:
(hs2_p3 - hs2_p2).norm()

tensor(0., device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<LinalgVectorNormBackward0>)

In [21]:
(hs2 - hs2_p).norm() / hs2.norm()

tensor(0.0025, device='cuda:0', dtype=torch.bfloat16, grad_fn=<DivBackward0>)

---

In [2]:
import torch


gate = torch.load('/root/work/axolotl/tests/tensor-eagle/gate.pt')
gate.shape

torch.Size([1, 14336])

In [3]:
up = torch.load('/root/work/axolotl/tests/tensor-eagle/up.pt')
up.shape

torch.Size([1, 14336])

In [4]:
gate_up = torch.load('/root/work/axolotl/tests/tensor-eagle/gate_up.pt')
gate_up.shape

torch.Size([1, 14336])